language: python
os:
- linux
python:
- '3.6'
install:
- pip install .
- pip install pytest
script: python -m pytest
deploy:
  provider: pypi
  user: magland
  on:
    tags: true
  password:
    secure: 0bGyp2LsjToyTNKM3OxZDHvz/r9DolhZJd8cb4nEaO5BOwKVmzEAr85tjsT1v5R+K+8Tyt/KE2aiXMEE3uxQNYUgHSsa3VZeewEGxTh/p2kJlOFEz8XDwnsNNm2Ya9FvkpOKs99qDF5u/rFt1fbNtBLrwVeFOJO32I0jYgSMTVBdZsX/ItMaH6zWbtw7fQCZUjIFL5KD5zuIlwsPfOg/KpAOmn3Zzpm5C8n/tkwcQmycuvnE8LV9HC6v9heS0FIMn0Ppf3rKki6K1yzFLgtCwCLa+OTIHzckSvXX3sL4G9ko3cBfLpla7TmoSQ81qtW6sEP7aI2yosOMV1sAvtrM2Xy/EpizHzM7Oaf5AsdNIPTblkCROuwsNs+dQvX4p/BHUD8bOZAAs17YVq5DtNVkye2tXpPbFe1F54xCQEzw/apAfKRUk3JTw9wZ3lxMTsh9E5+qPaikUNAxH0UHg8fLJm3vZrKFDGv4sPquv6wUhe40nbsWphleha1AkC72Lji8kN4rAQnyXCTckI5ptrL5jTyr1WOJtNsZd8KLK9ORfi7TOsm7pKEm4BCPQaAPtxRcJP3hR86MCaNglOXf/MO7oru0Niv7liGjhrfeCmVrhsP4GuWk1EUD4x+0m6C75sGTKAaIJfRQ3snF/970cNGsaAFR5kmTCgt3iz203Bi/0c8=
